api_platform:
    title: Hello API Platform
    version: 1.0.0
    eager_loading:
        max_joins: 200
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
