# config/packages/nelmio_cors.yaml
nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['http://localhost:8080', 'https://marsshop-ldax.onrender.com']
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    expose_headers: ['Link']
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: ['http://localhost:8080', 'https://marsshop-ldax.onrender.com']
      allow_headers: ['Content-Type', 'Authorization']
      allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
      max_age: 3600
